package com.starwacki.PixPulse.photo;

enum PhotoCategory {
    ARCHITECTURE,
    ANIMAL,
    GYM,
    LANDSCAPE,
    PORTRAITS,
    CITIES_AND_PLACES,
    STREET_ART,
    NATURE,
    TRAVEL,
    TECHNOLOGY,
    CULTURE_AND_TRADITIONS,
    AUTOMOTIVE,
    FASHION_AND_STYLE,
    HISTORICAL_ARCHIVE,
    CULINARY_ART,
    MACRO_PHOTOGRAPHY,
    FUN_AND_ENTERTAINMENT,
}
